### ISSUE TITLE
Server to Repository Connectivity

### ISSUE THREAD

**Issue by thomaspeterflood** [fuchsiana/ThreeBlindMice#1]
As it stands we have the 'ThreeBlindMice' repository. This repository has 1 administrator and 3 with Collaborator Access (as I understand it). Ideally, each collaborator should be able to pull from this repository to a server.

**Comment by fuchsiana** [comment]
There can only be one owner/admin of a GitHub repository; collaborators can do almost anything the admin can do, including the above. See here: https://help.github.com/articles/permission-levels-for-a-user-account-repository/

**Comment by thomaspeterflood** [comment]
I read your link. Here is what i discovered: 

Your personal github account identifies you as an individual user. as a user you can be granted permissions in repositories (such as the 'ThreeBlindMice' repo) and in organisations. Then, when you add an SSH key to your account you can identify yourself to the repo outside of the 'internet-browser' environment and therefore receive appropriate permissions. for example; being able to pull from the repository to a remote server. 

Solution: the owner and the collaborators need to add SSH keys to their own personal accounts by following this process ( https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ ). This will allow each user to pull from the repository remotely when necessary.

**Comment by thomaspeterflood** [comment]
Closing Issue since we have all managed to add the SSH protocol to our accounts and to push and pull successfully from the repo.
